import type { Metadata } from "next";
import { Abril_Fatface, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

export const abril = Abril_Fatface({ weight: "400", subsets: ["latin"] });
export const josefin = Josefin_Sans({ subsets: ["latin"], weight: "300" });
/*TODO Understanding how to add the meta without encountering the error: You are attempting to export "metadata" from a component marked with "use client", which is disallowed. Either remove the export, or the "use client" directive. Read more: https://nextjs.org/docs/getting-started/react-essentials#the-use-client-directive ;
// export const metadata: Metadata = {
//   title: "Nina Micle - Front End Developer",
//   description: "Generated by create next app",
// };*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
