import type { Metadata } from "next";
import { Abril_Fatface, Inter, Josefin_Sans } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const abril = Abril_Fatface({ weight: "400", subsets: ["latin"] });
export const josefin = Josefin_Sans({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Nina Micle - Front End Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefin.className}>{children}</body>
    </html>
  );
}
